In [1]:
import numpy as np

✅ Ejercicio 1 — Crear tu primer array.  
Crea un array con los números: `[1, 2, 3, 4, 5]`.  
Imprime:  
* el array
* su tipo

In [2]:
my_arr = np.array([1,2,3,4,5])

In [3]:
print(f"El array es de tipo {my_arr.dtype}")

El array es de tipo int64


✅ Ejercicio 2 — Dimensiones básicas.  
Crea este array:  
```py
[[1, 2, 3],
 [4, 5, 6]]
``` 
Imprime:
* ndim
* shape
* size

In [4]:
arr = np.arange(1,7).reshape(2,3)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(f"El array tiene {arr.ndim} dimensiones")

El array tiene 2 dimensiones


In [7]:
print(f"El array tiene la forma {arr.shape}")

El array tiene la forma (2, 3)


In [8]:
print(f"El array tiene un total de {arr.size} elementos")

El array tiene un total de 6 elementos


✅ Ejercicio 3 — Zeros, Ones, Full.  
Crea:  
* una matriz 3x3 de ceros
* una matriz 2x4 de unos
* una matriz 3x2 llena de 7
🎯 Objetivo: `zeros`, `ones`, `full`

matriz 3x3 de ceros

In [9]:
matriz_ceros = np.zeros((3,3))

In [10]:
matriz_ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

matriz 2x4 de unos

In [11]:
matriz_uno = np.ones((2,4))

In [12]:
matriz_uno

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

matriz 3x2 llena de 7

In [13]:
matriz_7 = np.full((3,2), 7)

In [14]:
matriz_7

array([[7, 7],
       [7, 7],
       [7, 7]])

✅ Ejercicio 4 — Arange y Linspace.  
Crea:  
* un array del 1 al 10 (sin incluir 10)
* un array de 5 números entre 0 y 1
🎯 Objetivo: `arange`, `linspace`

In [15]:
array_10 = np.arange(1,11)

In [16]:
array_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
array_5 = np.linspace(0,1,5)

In [18]:
array_5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])